image: rancher/build-cattle:v0.4.0
script:
  - ./scripts/ci
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/$$SLACK_WEBHOOK_TOKEN'
    username: 'Cattle-Build'
    channel: '#droneci'
    on_started: false
    on_success: true
    on_failure: true
